# Generated by Django 5.1.3 on 2026-08-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nookuser',
            name='auto_accept_friend_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nookuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nookuser',
            name='friend_request_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nookuser',
            name='message_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
