# Generated by Django 5.1.3 on 2025-06-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_friendship_created_at_friendship_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nookuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
