# Generated by Django 5.1.3 on 2025-08-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='users_hash',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
