# Generated by Django 5.1.3 on 2026-02-14 02:56

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_friendship_users_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friendship',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='status',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='users_hash',
        ),
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('from_user', 'to_user'), django.db.models.functions.comparison.Greatest('from_user', 'to_user'), name='unique_symmetric_friendship'),
        ),
    ]
