# Generated by Django 5.1.3 on 2026-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_friendship_unique_friendship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
