# Generated by Django 5.1.3 on 2025-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_message_metadata_message_type_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='participants_hash',
            field=models.CharField(default='default', editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
