# Generated by Django 5.1.3 on 2025-09-18 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookreview_rating'),
        ('threads', '0003_thread_participants_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.AddField(
            model_name='message',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content__isnull', False), ('book__isnull', True)), models.Q(('content__isnull', True), ('book__isnull', False)), _connector='OR'), name='message_either_content_or_book'),
        ),
    ]
