# Generated by Django 5.1.3 on 2025-09-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_remove_message_metadata_remove_message_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
