# Generated by Django 5.1.3 on 2025-10-06 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookreview_rating'),
        ('threads', '0005_rename_timestamp_message_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_either_content_or_book',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('content', ''), _negated=True), ('content__isnull', False), ('book__isnull', True)), models.Q(('content__isnull', True), ('book__isnull', False)), _connector='OR'), name='message_either_content_or_book'),
        ),
    ]
