# Generated by Django 5.1.3 on 2025-11-11 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookreview_rating'),
        ('threads', '0007_remove_message_message_either_content_or_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_either_content_or_book',
        ),
        migrations.AddField(
            model_name='message',
            name='thread_update',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content__gt', ''), ('content__isnull', False), _negated=True), models.Q(('book__isnull', True), models.Q(('thread_update__isnull', True), ('thread_update', ''), _connector='OR')), _connector='OR'), name='message_content_unique_field'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('book__isnull', False), _negated=True), models.Q(models.Q(('content__isnull', True), ('content', ''), _connector='OR'), models.Q(('thread_update__isnull', True), ('thread_update', ''), _connector='OR')), _connector='OR'), name='message_book_unique_field'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('thread_update__gt', ''), ('thread_update__isnull', False), _negated=True), models.Q(models.Q(('content__isnull', True), ('content', ''), _connector='OR'), ('book__isnull', True)), _connector='OR'), name='message_thread_update_unique_field'),
        ),
    ]
