# Generated by Django 5.1.3 on 2026-01-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_remove_message_message_either_content_or_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='participants_hash',
        ),
    ]
