# Generated by Django 5.1.3 on 2026-06-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_threadbookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadbookmark',
            old_name='created_at',
            new_name='placement',
        ),
    ]
