# Generated by Django 5.1.3 on 2026-06-04 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_rename_created_at_threadbookmark_placement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadbookmark',
            old_name='placement',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='threadbookmark',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threads.message'),
        ),
    ]
