# Generated by Django 5.1.3 on 2026-07-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_rename_placement_threadbookmark_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadbookmark',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='threads.message'),
        ),
    ]
