# Generated by Django 5.1.3 on 2025-03-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_remove_booklike_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review',
            field=models.TextField(max_length=2000),
        ),
    ]
