# Generated by Django 5.1.3 on 2025-04-09 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookreview_rating_delete_reviewlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BookLike',
        ),
    ]
