# Generated by Django 5.1.3 on 2026-09-01 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookreview_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookreview',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='unique_book_review'),
        ),
    ]
