# Generated by Django 5.1.3 on 2026-07-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='thumbnail',
        ),
    ]
