# Generated by Django 5.1.3 on 2026-04-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_title_alter_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('error', 'Error')], max_length=20),
        ),
    ]
