# Generated by Django 5.1.3 on 2026-05-04 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_friendship_accepted'),
        ('notifications', '0004_alter_notification_type'),
        ('threads', '0009_remove_thread_participants_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friendship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.friendship'),
        ),
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='threads.thread'),
        ),
    ]
